# Generated by Django 4.0.6 on 2022-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_category_color_alter_listing_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created']},
        ),
    ]
